INSIDER_TERMS = [
    "kek",
    "kekistan",
    "1488",
    "14 88",
    "bap", # Bronze Age Pervert
    "blood and soil",
    "gae", # Globalist American Empire
    "zog", # Zionist Occupied Government
    "wypipo",
    "soyjak",
    "femoid",
    "zog",
    "rino",
    "kang",
    "kangz",
    "negroid",
    "fiume",
    "gnc", # Global N***** Communism
]


SLURS = [
    "goyveyim",
    "goy",
    "goyim",
    "mongoloid",
    "fag",
    "phag",
    "faggot",
    "kike",
    "retard",
    "chink",
    "coon",
    "dyke",
]


KEYWORDS = [
    "activist",
    "alt right",
    "anglo",
    "anglophile",
    "antichrist",
    "antifa",
    "antiwhite",
    "anti-white",
    "american patriotism",
    "american way",
    "american whites",
    "attaq",
    "bap", 
    "beta male",
    "blacks",
    "black pill",
    "bloodthirsty",
    "blood and soil",
    "brother wars",
    "brotherhood",
    "cabal",
    "carnivore diet",
    "chad",
    "chadnet",
    "christ is king",
    "commie",
    "criminal"
    "cuck",
    "cuckface",
    "dark maga",
    "dei",
    "dissident right",
    "diversity",
    "daughters",
    "de",
    "drdavidduke",
    "eats babies",
    "elites",
    "european heritage",
    "evropean",
    "fag",
    "faggot",
    "fauci",
    "faustian spirit",
    "false flag",
    "fellow countrymen",
    "females",
    "femoid",
    "fiume",
    "fiumean",
    "foid",
    "gae", # Globalist American Empire
    "gigachad",
    "globalist",
    "globalism",
    "gnc", # Global N***** Communism
    "heil",
    "hillary",
    "hitler",
    "hoax",
    "ideology",
    "illegals",
    "illegal aliens",
    "illegal immigrants",
    "incest",
    "islamic extremists",
    "islamic radicals",
    "islamic terrorists",
    "islamist",
    "jab",
    "jewish",
    "jews",
    "jew",
    "jihadis",
    "jihadists",
    "kek",
    "kike",
    "liberal media",
    "locked up",
    "maga",
    "make america",
    "maniac",
    "marxist",
    "marxism",
    "marxist ideology",
    "mind control",
    "molesters",
    "multiculturalism",
    "muslim terrorists",
    "muslim",
    "mullahs",
    "nazi",
    "n word",
    "n-word",
    "new world order",
    "nigger",
    "normie",
    "npc",
    "osama bin laden",
    "patriot",
    "pedophile",
    "pizzagate",
    "phag",
    "pozzed",
    "pro-slavery",
    "protect children",
    "q right",
    "qanon",
    "race",
    "radical islamists",
    "radical islam",
    "radical left",
    "radical leftists",
    "rapist",
    "raw meat",
    "raw milk",
    "real american patriot",
    #"realdonaldtrump",
    "red pill",
    "reverse racism",
    "reverse racist",
    "richardbspencer",
    "pronoun crowd",
    "protect our children",
    "satan",
    "satanic",
    "sjw",
    "snowflake",
    "social justice warrior",
    "socialism",
    "socialist",
    "sodomites",
    "soros",
    "soyboy",
    "soy boy",
    "soyjak",
    "supplement",
    "sus",
    "testosterone",
    "terror attacks",
    "terrorist groups",
    "terrorist organizations",
    "terrorists",
    "traditional values",
    "tradwife",
    #"trump",
    "unpatriotic",
    "usa",
    "vitalist",
    "western civilization",
    "western values",
    "westernkind",
    "white",
    "white genocide",
    "white power",
    "white pride",
    "whites",
    "woke",
    "woke ideology",
    "wokeism",
    "wypipo",
    "youtube",
    "zog", # Zionist Occupied Government
    "#maga",
    "#altright",
    "#nationalsocialism",
    "#proslaverytwitter",
    "#whitegenocide",
    "#whitepower",
    "#whitelivesmatter",
    "#antiwhite",
    "agenda",
    "degenerate",
    "reich",
    "freemason",
    "masonic",
    "secret society",
    "pedos",
    "psychos",
    "psychopath",
    "goyveyim",
    "goy",
    "goyim",
    "deranged",
    "conspiracy",
    "disgusting",
    "neitzsche",
    "hail",
    "identity politics",
    "dissent",
    "thug",
    "negro",
    "negroid",
    "hollywierd",
    "brainwash",
    "3rd world invasion",
    "third world",
    "3rd world",
    "mongoloid",
    "cuckboi",
    "national socialist",
    "national socialism",
    "sharia law",
    "replace us",
    "erase us",
    "neomarxist",
    "colored",
    "coloured",
    "trigger",
    "triggered",
    "rino", # Republican In Name Only
    "kang",
    "kangz",
    "fake news",
    "yt ppl",
    "confederate",
    "confederacy",
    "david duke",
    "kkk",
    "retarded",
    "retard",
    "superior",
    "chink",
    "coon",
    "dyke",
    
]


# remove repetitive terms? there's probably a way to optimize word searching using regex
    # search for a word within other words, i.e. "marx" would capture "marxism", "neomarxist", etc.
    # punctuation too - i.e. "white" captures "white.", "!!white:)" etc.
# there are a lot of "normal" nazi tweets, ex: "QuiriniusR BellPottinger Wow quite an achievement..." how to filter them out?
# remove all tweets 3 words or less
# tweets in other languages - cut or translate?
# weighted random sampling
# subdividing keywords - 
    # 1) Literal nazi words (i.e. "fuhrer")
    # 2) Slurs, and lesser-known far right insider terms (like "kek" and "kang")
    # 3) Far right dog whistles sanitized for the general public (like "cultural marxism" and "dei hire")
    # 4) Classic GOP phrases (like "illegal aliens")
    # 5) General "political" words (like "Germany", or "Obama")
    # 6) mean words ("loser", "idiot")
    # 7) profanity (non-slurs)

# Twitter users to pull from:
# jordan peterson
# candace owens
# ben shapiro
# jk rowling
# 

# this could be used to prevent what happened to twitter from happening to bluesky

# obscure terms from https://www.reddit.com/r/AntifascistsofReddit/comments/10uprvw/a_glossary_of_lesser_known_alt_right_dogwhistles/?rdt=60012


STOPWORDS = [
    'a',
    'about',
    'above',
    'after',
    'again',
    'against',
    'ain',
    'all',
    'am',
    'an',
    'and',
    'any',
    'are',
    'aren',
    "aren't",
    'as',
    'at',
    'be',
    'because',
    'been',
    'before',
    'being',
    'below',
    'between',
    'both',
    'but',
    'by',
    'can',
    'couldn',
    "couldn't",
    'd',
    'did',
    'didn',
    "didn't",
    'do',
    'does',
    'doesn',
    "doesn't",
    'doing',
    'don',
    "don't",
    'down',
    'during',
    'each',
    'few',
    'for',
    'from',
    'further',
    'had',
    'hadn',
    "hadn't",
    'has',
    'hasn',
    "hasn't",
    'have',
    'haven',
    "haven't",
    'having',
    'he',
    "he'd",
    "he'll",
    'her',
    'here',
    'hers',
    'herself',
    "he's",
    'him',
    'himself',
    'his',
    'how',
    'i',
    "i'd",
    'if',
    "i'll",
    "i'm",
    'in',
    'into',
    'is',
    'isn',
    "isn't",
    'it',
    "it'd",
    "it'll",
    "it's",
    'its',
    'itself',
    "i've",
    'just',
    'll',
    'm',
    'ma',
    'me',
    'mightn',
    "mightn't",
    'more',
    'most',
    'mustn',
    "mustn't",
    'my',
    'myself',
    'needn',
    "needn't",
    'no',
    'nor',
    'not',
    'now',
    'o',
    'of',
    'off',
    'on',
    'once',
    'only',
    'or',
    'other',
    'our',
    'ours',
    'ourselves',
    'out',
    'over',
    'own',
    're',
    's',
    'same',
    'shan',
    "shan't",
    'she',
    "she'd",
    "she'll",
    "she's",
    'should',
    'shouldn',
    "shouldn't",
    "should've",
    'so',
    'some',
    'such',
    't',
    'than',
    'that',
    "that'll",
    'the',
    'their',
    'theirs',
    'them',
    'themselves',
    'then',
    'there',
    'these',
    'they',
    "they'd",
    "they'll",
    "they're",
    "they've",
    'this',
    'those',
    'through',
    'to',
    'too',
    'under',
    'until',
    'up',
    've',
    'very',
    'was',
    'wasn',
    "wasn't",
    'we',
    "we'd",
    "we'll",
    "we're",
    'were',
    'weren',
    "weren't",
    "we've",
    'what',
    'when',
    'where',
    'which',
    'while',
    'who',
    'whom',
    'why',
    'will',
    'with',
    'won',
    "won't",
    'wouldn',
    "wouldn't",
    'y',
    'you',
    "you'd",
    "you'll",
    'your',
    "you're",
    'yours',
    'yourself',
    'yourselves',
    "you've",
]